### PR TITLE
Update Modular Turrets and Salvaged Robots to match Mainline style and uncraft recipes Fixes #35689 

### PR DESCRIPTION
**Pull request by CSHague**
#### Summary
SUMMARY: Mods "Align Modular Turrets craft and uncraft recipes with new changes to mainline robots and turrets"
#### Purpose of change
Originally intended to fix an issue #35689 - Modular Turrets and Salvaged Robots uncraft recipes contain outdated uncraft recipes that prevent the player from accessing newer items that are components for newer recipes. Eventually turned into an update to get Modular Turrets and Salvaged Robots to match Mainline turret style in terms of uncrafting recipes and ammo drops. 
#### Describe the solution.

- Specifically tried to keep the power sources the same, except for with manhacks which were converted to  use small storage batteries. Plutonium batteries not merged from many entries as microreactors can be uncrafted into plutonium cells.

 -  Modified the uncraft recipes of broken turrets and robots so they will disassemble into newer components to allow the player to access the Turret Control Unit and other future items :
Any turret or robot that can fire a ranged weapon was given targeting and gun control modules; AI cores and other robotic modules were added to the recipes trying to match the tiers shown in main: Simple core for manhacks, regular for turrets and guard bots, and advanced cores for medical robots;  many loose electronics were removed from the disassembly recipes as the new modules can be uncrafted for the same electronic components and turrets and robots were given new chassis components (spider legs, reverse-jointed legs, android arms, et al) As a result scrap metal and electronics removed as these components clearly represent the body. The body parts I couldn't find a rough analogue for I kept as scrap components.

- Military Turrets and robots have had their starting_ammunition increased to approximate with the mainline turrets, 1000 for 308, 1600 for 556. Liquid turrets have been given 10L of ammunition equivalent to a plastic jerrycan. Small pillbox turrets were kept with low capacities as they appear to be "civilian models." Grenade launchers were kept at their default capacities. 

- Added DROPS_AMMO to many turrets allowing them to drop the same amount of ammo as turrets in mainline. This would at least give the player access to a wider variety of ammunition over the military and civilian-use spectrum. Tried to match ammunition volume wise with the mainline turrets.

- Lights were removed from turrets and robots to match mainline turrets. This would be a good spot for another branch to add a craftable spotlight turret.

#### Describe alternatives you've considered

With the breadth of changes made it's hard to speak for alternatives. Removing the override on the corpses would allow the player to salvage regular turrets but they would lose the functionality of the modular turrets. I guess leaving the Modular Turrets deprecated would be considered a reprieve from what some would consider newer "unfair" turrets.

#### Testing
Put this branch through its paces.  Turrets properly drop their ammo when killed except for liquid turrets which is the source of a duping bug and was subsequently disabled. Craftbuddy uses Batteries as ammo, rendering it impossible to load though it doesn't appear to need the ammo to do anything. Updating the craftbuddy is out of the scope of this branch.

#### Additional context
Came across this issue a few days ago while watching a streamer and wanted to take a crack at handling it. This is my first fork and since this is just a JSON edit (while large) it seemed doable. Could use some input on the broken cyborg. 

I eschewed many of the robotic modules in the broken cyborg recipes, as one would expect the human brain component is responsible for most of that, but I added robotic controls to, as some subsystem must be responsible for forcing the cyborg to do things. If I should add an AI core to it as well, that is fine.

Weights and volumes of monsters to the new components needs to be added still but I feel like I'm on a good clip with this so far.

### CODE REVIEW

**Comment by Maleclypse** [comment]
Super glad you decided to take this on as I've been working on several different ways to approach it.  The only thing I notice is that you didn't update the Salvaged Robots recipes to utilize the standard modules that are now uncrafted from bot corpses.  I can look at it some more tonight probably. 
EDIT: I also did not see anything in here that fixes the current issue of Modular Turrets causing no ammo to drop from any turret or bot. Which can probably be solved by just adding a random amount of the appropriate ammo to drop.

**Comment by Maleclypse** [comment]
Also you have put this PR on your own repo so unless someone looks at the issue and follows the link no one will come to this.  You need to pull the PR to CleverRaven.

**Comment by CSHague** [comment]
Thanks! This is really my first time doing this stuff (git and all that) so it's been a learning experience. I'll keep working on the bits you mentioned. As for the ammo, I guess I should look at how much ammo the mainline turrets drop and work accordingly? It always did seem like a lot of ammo but I guess that's what is intended with the new turrets.

**Comment by CSHague** [comment]
I've looked at the bot recipes and most appear to already include a disarmed version of a salvage robot, which implies that the parts that you are adding to it are replacements for broken or slagged components or are additions to the frame. I added the modules to all the disarmed base robots so you shouldn't need to add them twice, maybe just replace a fried chip or two in each individual one. Since there's no way to do that easily without creating a whole set of faults for salvaged components (which is actually a neat idea, imagine a robot with faulty pathfinding modules that keeps bumping into walls) I just kept the recipes the same. The only recipes that should get their own modules are the autoarmor recipes (Something I was gonna do until I had to go to bed :P)

**Comment by Maleclypse** [comment]
https://jsonlint.com/?json=  This will make sure your syntax works in json.   Then once it works copy and paste the whole mess into this http://dev.narc.ro/cataclysm/format.html  this makes sure it fits the JSON style check.  Once it succeeds in the cataclysm linter you're basically ready to do a Pull request to CleverRaven.  :) make sure to copy and paste from the cataclysm linter back into your files even if it doesn't look like much changed.

**Comment by CSHague** [comment]
Haha, you posted that just as I was reading the style guide. Thanks for the help

**Comment by Maleclypse** [comment]
No problem. If you get stuck on something let me know and I'll try to see if I can figure out what's wrong.

**Comment by CSHague** [comment]
Yeah, I dunno what's happening here. Validator keeps saying that the linting isn't working. JSON is valid linted in the Linting tool but validator tells me to lint again

**Comment by Maleclypse** [comment]
It won't let me edit directly but it looks like you have two empty lines at the end of uncraft corpses that have a single space each in them.  Sometimes that is a problem.

**Comment by Maleclypse** [comment]
Can you make me a reviewer?  I think that will let me recommend changes directly to the files.

**Comment by CSHague** [comment]
Gah, I have javascript blocked and Github uses hidden javascript servers. I have to figure out which one it is that operates the widget on the right. Hold on.

**Comment by CSHague** [comment]
I assigned you. I couldn't add you as a reviewer... for some reason.

**Comment by Maleclypse** [comment]
Try this for PR Validator   SUMMARY:  Content "Align Modular Turrets craft and uncraft recipes with new changes to master robots and turrets"  Also looks like you fixed your JSON validation :)!

**Comment by CSHague** [comment]
Yeah, it was the spaces like you said. I'll be more aware of that in the future.

**Comment by Maleclypse** [comment]
I'm going to have to figure out how to review and suggest changes because it makes it much easier to show.  I tried googling it and it's way more than I can grasp right before bedtime, but seriously this is good stuff especially for a first contribution.  Hopefully the CI build is successful and let me know if you need advice tomorrow on how to set a PR to CleverRaven repository so you get it into the mainline.

**Comment by Maleclypse** [comment]
Looks like this is ready to get remade as a PR for CleverRaven. I'm excited to be able to start creating worlds with Salvaged Turrets and Modular Robots enabled again.  :)

**Comment by CSHague** [comment]
Gonna have to make some adjustments after testing. It seems the DROPS_AMMO flag will drop fluid ammunition in a full container per unit of remaining ammo. Setting the starting ammo on the flamer bots to 200 left 200 plastic jerrycans filled with napalm on kill, which was a very interesting sight. I will have to do more testing to see just how much ammo X number of liquid ammo really is for a turret in terms of shots.

**Pull request closed without merging**
